// Explanations and examples are original editorial content. The displayed
// signatures deliberately illustrate one overload, not every standard overload.
const entry = (
    id,
    name,
    version,
    header,
    category,
    summary,
    analogy,
    signature,
    body,
    output,
    input,
    note,
    section,
    file = "algorithms",
) => ({
    id,
    name,
    version,
    header,
    category,
    summary,
    analogy,
    signature,
    example: `${[...new Set([header, "iostream", ...(body.includes("std::vector") ? ["vector"] : []), ...(body.includes("std::string") ? ["string"] : [])])].map((value) => `#include <${value}>`).join("\n")}\n\nint main() {\n${body
        .split("\n")
        .map((line) => `    ${line}`)
        .join("\n")}\n}\n`,
    output,
    input,
    note,
    source: { file, section },
});

export const versions = ["98", "11", "14", "17", "20", "23"];
export const entries = [
    entry(
        "sort",
        "std::sort",
        "98",
        "algorithm",
        "Algorithms",
        "Put a collection in order.",
        "Like arranging a bookshelf from the smallest book to the tallest. The same items stay on the shelf, just in a new order.",
        "template<class RandomIt>\nvoid sort(RandomIt first, RandomIt last);",
        'std::vector<int> scores = {42, 12, 85, 27};\nstd::sort(scores.begin(), scores.end());\nfor (int score : scores) {\n    std::cout << score << " ";\n}',
        "12 27 42 85 ",
        "A list of scores: 42, 12, 85, 27",
        "Changes the original collection. The end iterator is excluded. Equal items may change their relative order; use stable_sort when that matters.",
        "sort",
    ),
    entry(
        "find",
        "std::find",
        "98",
        "algorithm",
        "Algorithms",
        "Find the first item you are looking for.",
        "Like scanning a shopping list until you spot milk. You get its position, or a signal that it was not on the list.",
        "template<class InputIt, class T>\nInputIt find(InputIt first, InputIt last, const T& value);",
        'std::vector<int> numbers = {4, 8, 15};\nauto position = std::find(numbers.begin(), numbers.end(), 8);\nstd::cout << (position != numbers.end() ? "Found" : "Not found");',
        "Found",
        "Find 8 in the list 4, 8, 15",
        "Always compare the result with end() before reading the item. end() is a position after the last item.",
        "alg.find",
    ),
    entry(
        "count",
        "std::count",
        "98",
        "algorithm",
        "Algorithms",
        "Count how often a value appears.",
        "Like counting the red marbles in a jar without taking any out.",
        "template<class InputIt, class T>\nauto count(InputIt first, InputIt last, const T& value)\n    -> typename std::iterator_traits<InputIt>::difference_type;",
        "std::vector<int> votes = {1, 2, 1, 3, 1};\nstd::cout << std::count(votes.begin(), votes.end(), 1);",
        "3",
        "Votes: 1, 2, 1, 3, 1; count the 1s",
        "Visits every item once. It does not change the collection.",
        "alg.count",
    ),
    entry(
        "reverse",
        "std::reverse",
        "98",
        "algorithm",
        "Algorithms",
        "Turn a sequence around.",
        "Like reading a row of cards from right to left, then placing them in that order.",
        "template<class BidirIt>\nvoid reverse(BidirIt first, BidirIt last);",
        'std::string word = "hello";\nstd::reverse(word.begin(), word.end());\nstd::cout << word;',
        "olleh",
        'The text "hello"',
        "Changes the original sequence. Reversing UTF-8 bytes is not a safe way to reverse human-language characters.",
        "alg.reverse",
    ),
    entry(
        "accumulate",
        "std::accumulate",
        "98",
        "numeric",
        "Numbers",
        "Add up a collection of values.",
        "Like adding each receipt to a running total. Start at zero, or at a balance you already have.",
        "template<class InputIt, class T>\nT accumulate(InputIt first, InputIt last, T initial);",
        "std::vector<int> prices = {12, 8, 5};\nstd::cout << std::accumulate(prices.begin(), prices.end(), 0);",
        "25",
        "Prices: 12, 8, 5; starting total: 0",
        "The initial value determines the accumulator type. Use 0.0 to add floating-point values without truncating them.",
        "accumulate",
        "algorithms",
    ),
    entry(
        "sqrt",
        "std::sqrt",
        "98",
        "cmath",
        "Numbers",
        "Find the square root of a number.",
        "If a square has an area of 81, its side length is 9. This function finds that side length.",
        "double sqrt(double value);",
        "std::cout << std::sqrt(81.0);",
        "9",
        "An area of 81",
        "For real-number calculations, supply a nonnegative value. Negative input causes a domain error.",
        "c.math",
        "numerics",
    ),
    entry(
        "all-of",
        "std::all_of",
        "11",
        "algorithm",
        "Algorithms",
        "Check whether every item passes a test.",
        "Like checking that every guest has a ticket before opening the doors.",
        "template<class InputIt, class Predicate>\nbool all_of(InputIt first, InputIt last, Predicate test);",
        "std::vector<int> ages = {21, 30, 18};\nbool adults = std::all_of(ages.begin(), ages.end(), [](int age) {\n    return age >= 18;\n});\nstd::cout << std::boolalpha << adults;",
        "true",
        "Ages: 21, 30, 18; minimum age: 18",
        "An empty collection returns true because no item fails the test.",
        "alg.all.of",
    ),
    entry(
        "any-of",
        "std::any_of",
        "11",
        "algorithm",
        "Algorithms",
        "Check whether at least one item passes a test.",
        "Like checking whether any seat on a train is still available.",
        "template<class InputIt, class Predicate>\nbool any_of(InputIt first, InputIt last, Predicate test);",
        "std::vector<int> seats = {0, 0, 3};\nbool available = std::any_of(seats.begin(), seats.end(), [](int count) {\n    return count > 0;\n});\nstd::cout << std::boolalpha << available;",
        "true",
        "Available seats in each carriage: 0, 0, 3",
        "An empty collection returns false. The search can stop at the first matching item.",
        "alg.any.of",
    ),
    entry(
        "to-string",
        "std::to_string",
        "11",
        "string",
        "Text",
        "Turn a number into text.",
        "Like writing a number on a label so you can combine it with other words.",
        "std::string to_string(int value);",
        'int points = 42;\nstd::cout << "Score: " + std::to_string(points);',
        "Score: 42",
        "A score of 42",
        "This example uses the integer overload. Floating-point formatting has version-dependent behavior; use format when precise formatting matters.",
        "string.conversions",
        "strings",
    ),
    entry(
        "iota",
        "std::iota",
        "11",
        "numeric",
        "Numbers",
        "Fill a sequence with consecutive values.",
        "Like numbering a row of seats, starting with a number you choose.",
        "template<class ForwardIt, class T>\nvoid iota(ForwardIt first, ForwardIt last, T value);",
        'std::vector<int> seats(4);\nstd::iota(seats.begin(), seats.end(), 1);\nfor (int seat : seats) {\n    std::cout << seat << " ";\n}',
        "1 2 3 4 ",
        "Four empty positions; start at 1",
        "The destination must already have space. iota assigns values; it does not grow the collection.",
        "numeric.iota",
        "algorithms",
    ),
    entry(
        "make-unique",
        "std::make_unique",
        "14",
        "memory",
        "Memory",
        "Create an object with one automatic owner.",
        "Like giving a single person the key to a locker. When that owner leaves, the locker is cleaned up automatically.",
        "template<class T, class... Args>\nstd::unique_ptr<T> make_unique(Args&&... args);",
        "auto score = std::make_unique<int>(42);\nstd::cout << *score;",
        "42",
        "An integer with the value 42",
        "A unique_ptr cannot be copied. Ownership can be transferred with std::move.",
        "unique.ptr.create",
        "memory",
    ),
    entry(
        "exchange",
        "std::exchange",
        "14",
        "utility",
        "Utilities",
        "Replace a value and get the old one back.",
        "Like changing a sign from open to closed while keeping the old sign in your hand.",
        "template<class T, class U = T>\nT exchange(T& object, U&& new_value);",
        'int score = 10;\nint previous = std::exchange(score, 20);\nstd::cout << previous << " -> " << score;',
        "10 -> 20",
        "Old score: 10; new score: 20",
        "This is not an atomic operation. It does not synchronize access between threads.",
        "utility.exchange",
        "utilities",
    ),
    entry(
        "clamp",
        "std::clamp",
        "17",
        "algorithm",
        "Algorithms",
        "Keep a value inside a chosen range.",
        "Like a volume control that cannot go below 0 or above 100, even when you ask it to.",
        "template<class T>\nconst T& clamp(const T& value, const T& low, const T& high);",
        "int volume = 120;\nstd::cout << std::clamp(volume, 0, 100);",
        "100",
        "Volume: 120; allowed range: 0 to 100",
        "The lower bound must not exceed the upper bound. Copy the result when passing temporary values; keeping the returned reference can dangle.",
        "alg.clamp",
    ),
    entry(
        "gcd",
        "std::gcd",
        "17",
        "numeric",
        "Numbers",
        "Find the biggest whole number that divides both values.",
        "Like finding the largest equal-sized groups you can make from two piles without leftovers.",
        "template<class M, class N>\nstd::common_type_t<M, N> gcd(M first, N second);",
        "std::cout << std::gcd(24, 36);",
        "12",
        "Two piles containing 24 and 36 items",
        "Accepts integer types other than bool. Absolute values must be representable in the common type.",
        "numeric.ops.gcd",
        "algorithms",
    ),
    entry(
        "lcm",
        "std::lcm",
        "17",
        "numeric",
        "Numbers",
        "Find the smallest shared multiple.",
        "Two lights blink every 4 and 6 seconds. They blink together again after 12 seconds.",
        "template<class M, class N>\nstd::common_type_t<M, N> lcm(M first, N second);",
        "std::cout << std::lcm(4, 6);",
        "12",
        "Intervals of 4 and 6 seconds",
        "The result and the absolute inputs must fit in the common integer type. A zero input produces zero.",
        "numeric.ops.lcm",
        "algorithms",
    ),
    entry(
        "size",
        "std::size",
        "17",
        "iterator",
        "Containers",
        "Ask a collection how many items it holds.",
        "Like checking the number of eggs in a carton without counting them yourself.",
        "template<class C>\nconstexpr auto size(const C& container)\n    -> decltype(container.size());",
        "std::vector<int> eggs = {1, 2, 3, 4, 5, 6};\nstd::cout << std::size(eggs);",
        "6",
        "A collection of six eggs",
        "Works with standard containers and built-in arrays. It does not count elements behind a raw pointer.",
        "iterator.range",
        "iterators",
    ),
    entry(
        "midpoint",
        "std::midpoint",
        "20",
        "numeric",
        "Numbers",
        "Find the halfway point without overflowing.",
        "Like meeting a friend halfway between two street numbers.",
        "template<class T>\nconstexpr T midpoint(T first, T second) noexcept;",
        "std::cout << std::midpoint(10, 20);",
        "15",
        "Street numbers 10 and 20",
        "For integers, an odd sum rounds toward the first argument. Unlike (a + b) / 2, the addition cannot overflow.",
        "numeric.ops.midpoint",
        "algorithms",
    ),
    entry(
        "starts-with",
        "std::string::starts_with",
        "20",
        "string",
        "Text",
        "Check whether text begins with a prefix.",
        "Like checking the first few letters on an envelope to see whether it belongs in a particular stack.",
        "constexpr bool starts_with(const char* prefix) const;",
        'std::string filename = "report.pdf";\nstd::cout << std::boolalpha << filename.starts_with("report");',
        "true",
        "File name: report.pdf; prefix: report",
        "The comparison is case-sensitive. An empty prefix always matches.",
        "string.starts.with",
        "strings",
    ),
    entry(
        "ends-with",
        "std::string::ends_with",
        "20",
        "string",
        "Text",
        "Check whether text ends with a suffix.",
        "Like looking at the end of a file name to recognize its extension.",
        "constexpr bool ends_with(const char* suffix) const;",
        'std::string filename = "photo.png";\nstd::cout << std::boolalpha << filename.ends_with(".png");',
        "true",
        "File name: photo.png; suffix: .png",
        "The comparison is case-sensitive. A file extension alone does not verify the actual file format.",
        "string.ends.with",
        "strings",
    ),
    entry(
        "popcount",
        "std::popcount",
        "20",
        "bit",
        "Bits",
        "Count the switched-on bits in a number.",
        "Imagine a row of tiny switches. This tells you how many are turned on.",
        "template<class T>\nconstexpr int popcount(T value) noexcept;",
        "unsigned int flags = 13; // Binary: 1101\nstd::cout << std::popcount(flags);",
        "3",
        "13, written as 1101 in binary",
        "The input must be an unsigned integer type. It counts binary ones, not decimal digits.",
        "bit.count",
        "utilities",
    ),
    entry(
        "contains",
        "std::string::contains",
        "23",
        "string",
        "Text",
        "Check whether text contains a word or phrase.",
        "Like looking for a word on a page; you only need a yes or no answer.",
        "constexpr bool contains(const char* text) const;",
        'std::string message = "Hello, C++ explorer!";\nstd::cout << std::boolalpha << message.contains("explorer");',
        "true",
        "Message: Hello, C++ explorer!; search: explorer",
        "The comparison is case-sensitive. An empty search string always matches.",
        "string.contains",
        "strings",
    ),
    entry(
        "byteswap",
        "std::byteswap",
        "23",
        "bit",
        "Bits",
        "Reverse the bytes inside an integer.",
        "Like reversing the order of the boxes in a delivery, while leaving the contents of each box alone.",
        "template<class T>\nconstexpr T byteswap(T value) noexcept;",
        "unsigned short value = 0x1234;\nstd::cout << std::hex << std::byteswap(value);",
        "3412",
        "The two-byte hexadecimal value 0x1234",
        "This example assumes a 16-bit unsigned short. The type must be integral and have no padding bits.",
        "bit.byteswap",
        "utilities",
    ),
    entry(
        "to-underlying",
        "std::to_underlying",
        "23",
        "utility",
        "Utilities",
        "Get the number stored behind an enum value.",
        "Like reading the numeric code behind a named label.",
        "template<class T>\nconstexpr std::underlying_type_t<T> to_underlying(T value) noexcept;",
        "enum class Status : int { ready = 1, done = 2 };\nstd::cout << std::to_underlying(Status::done);",
        "2",
        "The named status Status::done",
        "Only enumeration types are accepted. The returned type is the underlying type of that enum.",
        "utility.underlying",
        "utilities",
    ),
    entry(
        "print",
        "std::print",
        "23",
        "print",
        "Input / output",
        "Print a neatly formatted message.",
        "Like filling the blanks in a sentence with the values you want to share.",
        "template<class... Args>\nvoid print(std::format_string<Args...> format, Args&&... args);",
        'std::print("Hello, {}! You have {} points.", "Alex", 42);',
        "Hello, Alex! You have 42 points.",
        "Name: Alex; points: 42",
        "Requires a standard library with C++23 print support. Unlike println, print does not add a newline.",
        "print.fun",
        "iostreams",
    ),
];
